# theme = "autumn"
theme = "gruvbox"

[editor]
line-number = "relative"
mouse = true

[keys.normal]
"C-c" = ["keep_primary_selection", "collapse_selection"]

[keys.insert]
"C-c" = "normal_mode"

[keys.select]
"C-c" = ["normal_mode", "keep_primary_selection", "collapse_selection"]
