#!/usr/bin/bash

LAPTOP="eDP-1"
EXTERNAL=$(xrandr --query | awk -v laptop="$LAPTOP" '/ connected / && $1 != laptop {print $1; exit}')

if [ -n "$EXTERNAL" ]; then
    xrandr --output $LAPTOP --auto \
        --output $EXTERNAL --auto --right-of $LAPTOP
else
    # xrandr --output $LAPTOP --auto
    xrandr --auto
fi
