#!/usr/bin/bash

sudo dnf install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
sudo systemctl enable --now docker
sudo docker run hello-world
sudo docker ps

sudo usermod -aG docker $USER
newgrp docker
