#!/usr/bin/env bash
set -e  # Exit on error
set -o pipefail

sudo dnf install erlang

cd ~/repos

# download the latest release of elixir from github
URL=$(curl -s https://api.github.com/repos/elixir-lang/elixir/releases/latest \
  | jq -r '.assets[] | select(.name | test("\\.tar\\.gz$")) | .browser_download_url')

curl -LO "$URL" 

FILENAME=$(basename "$URL")
tar -xvzf "$FILENAME"
rm "$FILENAME"

EXTRACTED_DIR=$(tar -tzf "$FILENAME" | head -n1 | cut -d/ -f1)
cd "$EXTRACTED_DIR"
make clean compile

mkdir ~/.local/bin/elixir
mv ./bin ~/.local/bin/elixir

~/.local/bin/elixir/elixir --version
