#!/usr/bin/env bash
set -e  # Exit on error
set -o pipefail

sudo dnf install erlang

cd ~/repos

git clone --branch v1.18 --single-branch git@github.com:elixir-lang/elixir.git 
cd ~/repos/elixir
make clean compile

mkdir ~/.local/bin/elixir
mv ./bin ~/.local/bin/elixir

~/.local/bin/elixir/elixir --version
