#!/usr/bin/bash

sudo dnf install java-21-openjdk-devel

# scala
curl -fL https://github.com/coursier/coursier/releases/latest/download/cs-x86_64-pc-linux.gz | gzip -d > cs && chmod +x cs && ./cs setup
