#!/usr/bin/bash

REPO="zen-browser/desktop"

LATEST_TAG=$(curl -s "https://api.github.com/repos/$REPO/releases/latest" | jq -r '.tag_name')
FILE_NAME="zen-x86_64.AppImage"
DOWNLOAD_URL="https://github.com/$REPO/releases/download/$LATEST_TAG/$FILE_NAME"

curl -L -o zen "$DOWNLOAD_URL"

sudo chmod +x ./zen
sudo mv -f ./zen /usr/local/bin/

